[Script]
http-response ^https?:\/\/(car\.cq-ct\.com|www\.cq-ct\.tech|shop\.btcl-tec\.com|test-tsp\.btcl-tec\.com)(:\d+)?\/ script-path=%SCRIPT_PATH%,requires-body=true,timeout=20,tag=南方智行订阅验证,argument="mode=observe-full&notify=1&strict=1&target=both",enable=true

[MITM]
hostname = car.cq-ct.com,www.cq-ct.tech,shop.btcl-tec.com,test-tsp.btcl-tec.com
